spring:
  thymeleaf:
    prefix : file:src/main/resources/templates/

  datasource:
    data-source-class-name: org.h2.Driver
    url: jdbc:h2:mem:its;DB_CLOSE_ON_EXIT=TRUE;MODE=MySQL
    username: sa
    password:
